const STREAMSHELF_SEED = [
  { id: "m1", title: "Blue Hour", tagline: "Every sunset hides a secret.", type: "Series", genre: "Drama", platform: "Hulu", mood: "Moody", status: "Watching", rating: 4.7, episodes: 10, watched: 6, runtime: 48, note: "Slow-burn mystery with pretty cinematography and a weekly cliffhanger feel.", color: "#63d2ff", accent: "#ff6f61", poster: "moon", preview: "Foggy coastline, missing journal, and one final clue before midnight." },
  { id: "m2", title: "City Lights Club", tagline: "A comedy about one chaotic friend group.", type: "Movie", genre: "Comedy", platform: "Netflix", mood: "Fun", status: "Watchlist", rating: 4.2, episodes: 1, watched: 0, runtime: 112, note: "Good for a low-stress Friday night when the goal is easy laughs.", color: "#ff5e9c", accent: "#ffc371", poster: "city", preview: "Rooftop jokes, late trains, and a night out that refuses to go as planned." },
  { id: "m3", title: "Signal Run", tagline: "The message was never meant to arrive.", type: "Series", genre: "Sci-Fi", platform: "Prime", mood: "Intense", status: "Favorite", rating: 4.9, episodes: 8, watched: 8, runtime: 52, note: "Smart pacing, big finale, and the kind of ending worth rewatching.", color: "#9cff6e", accent: "#3de0d0", poster: "signal", preview: "Encrypted transmissions, runaway tech, and a crew racing the clock." },
  { id: "m4", title: "Soft Serve Summer", tagline: "Small town, big feelings, extra sprinkles.", type: "Movie", genre: "Romance", platform: "Max", mood: "Cozy", status: "Finished", rating: 4.1, episodes: 1, watched: 1, runtime: 96, note: "Cute comfort watch with bright visuals and a breezy weekend tone.", color: "#ffe56b", accent: "#ff9f6e", poster: "sun", preview: "Beach bikes, pastel sunsets, and a second chance that feels easy." },
  { id: "m5", title: "Archive 77", tagline: "Some tapes should stay buried.", type: "Series", genre: "Thriller", platform: "Apple TV", mood: "Suspense", status: "Watchlist", rating: 4.5, episodes: 9, watched: 0, runtime: 44, note: "Queued for a weekend binge when a darker mystery sounds right.", color: "#a78bfa", accent: "#f2c4ce", poster: "archive", preview: "Old footage, locked rooms, and a pattern nobody wants to name." },
  { id: "m6", title: "Kitchen Passport", tagline: "Recipes that travel without a boarding pass.", type: "Series", genre: "Lifestyle", platform: "Disney+", mood: "Chill", status: "Watching", rating: 4.3, episodes: 12, watched: 3, runtime: 31, note: "Easy background watch with travel, food, and low-pressure episodes.", color: "#ff9f6e", accent: "#9cff6e", poster: "plate", preview: "Market mornings, family recipes, and simple meals with a story." },
  { id: "m7", title: "After Midnight Arcade", tagline: "The game starts when the city sleeps.", type: "Series", genre: "Action", platform: "Peacock", mood: "High Energy", status: "Watchlist", rating: 4.6, episodes: 6, watched: 0, runtime: 42, note: "Fast, neon, and perfect for a night where quiet drama is not the move.", color: "#00f0ff", accent: "#ff5e9c", poster: "arcade", preview: "Neon alleys, speed runs, and one tournament with real-world stakes." },
  { id: "m8", title: "The Little Observatory", tagline: "A quiet film about looking up.", type: "Movie", genre: "Documentary", platform: "YouTube", mood: "Curious", status: "Watchlist", rating: 4.4, episodes: 1, watched: 0, runtime: 74, note: "A calm science pick for when curiosity wins over another scripted series.", color: "#f2c4ce", accent: "#63d2ff", poster: "stars", preview: "Backyard telescopes, patient teachers, and the wonder of a clear sky." }
];

if (typeof globalThis !== "undefined") globalThis.STREAMSHELF_SEED = STREAMSHELF_SEED;
if (typeof module !== "undefined") module.exports = STREAMSHELF_SEED;
